services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=False
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESSS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME}
    volumes:
      - static_volume:/vol/web/static
    depends_on:
      - nginx

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/vol/web/static
      - certs:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - certbot
    environment:
      - NGINX_HOST=api.theoklahomahandyman.com
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}

  certbot:
    image: certbot/certbot
    volumes:
      - certs:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    entrypoint: >
      certbot certonly --webroot --webroot-path=/var/www/certbot
      --email ${EMAIL_ADDRESS} --agree-tos --no-eff-email
      -d api.theoklahomahandyman.com

volumes:
  static_volume:
