name: Dev Testing Pipeline

on:
  push:
    branches:
      - dev

jobs:
  test-backend:
    runs-on: ubuntu-latest
    env:
      DEBUG: "True"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Dependencies
        working-directory: back-end
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Up Environment Variables
        working-directory: back-end
        run: |
          echo "DEBUG=$DEBUG" > back-end/.env

      - name: Run Tests With Coverage
        working-directory: back-end
        run: |
          source .venv/bin/activate
          coverage run manage.py test
          coverage report --fail-under=80
